### ISSUE TITLE
 AIR-MOT dataset 

### ISSUE THREAD

**Issue by Wolfe233** [LingyvKong/CFTracker#2]
Can you give the unconverted AIR-MOT dataset file structure?

**Comment by Wolfe233** [comment]
Can you share the air-mot dataset

**Comment by LingyvKong** [comment]
For questions related to the AIR-MOT dataset, please consult the original author. 

Some friends wanted to know my train-test split, so I showed the first frame of the testset I used: 
![image](https://github.com/LingyvKong/CFTracker/assets/35091237/09dc26ce-4810-47b4-a35c-76fec514a36f)

**Comment by Wolfe233** [comment]
How to get 46 test videos and 106 training videos from raw data ？
